interface Flashcard {
    void Flashcard();
    attribute unsigned long repetition;
    attribute unsigned long interval;
    attribute float easinessFactor;
    attribute unsigned long long previousDate;
    attribute unsigned long long nextDate;
};

interface FlashcardGrader {
    [Value] static Flashcard gradeFlashcard(
        [Ref] Flashcard flashcard,
        unsigned long grade,
        unsigned long long currentDatetime
    );
};
